### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by Jyuart** [Jyuart/homepage#5]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by nathanmorgandrake** [comment]
Nathan "Nate" Drake (born Nathan Morgan) is the main protagonist and playable character of the Uncharted series. A former professional treasure hunter, Nate is described as a "deep-sea salvage expert and action-pro". Since childhood, Nate and his older brother Samuel Drake have held the belief that they are descended from the famous English explorer Sir Francis Drake. As of the events of Drake's Deception, Drake is married to Elena Fisher, and after the events of A Thief's End, the two have a daughter named Cassie Drake.

**Comment by nathanmorgandrake** [comment]
ndi-dog@naughtydog.com.
https://www.instagram.com/nate_drake_official/
