### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by Jyuart** [Jyuart/homepage#8]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by nathanmorgandrake** [comment]
**I'm tired of writing it, so find everything else you need by yourself. I'm quite famous so that won't be difficult.**

Achievements
One of the 25 best new characters of the decade by GamesRadar
#22 in "50 greatest video games characters" by Empire
#3 "most memorable, influential, and badass" protagonist in games by GamesRadar
#4 in "Greatest Game Hero" by Game Informer's poll
#16 in top video game character of all time by the readers of Guinness World Records Gamer's Edition 
Languages
English, Latin, 16th century Spanish
Skill
Joking, jumping, shooting, charming, searching for treasures, intelligence, hand to hand combat, vehicular skills, skilled thief
Character
Every-man, humorous, optimistic, expressive, charismatic, dreamy
Likes
Jokes, treasure hunting, adventures, breaking old artifacts
Dislikes
Old curses, routine work, betrayers
